<?php

namespace App\Http\Controllers\User\MyTeam;

use App\Http\Controllers\Controller;
use App\Http\Controllers\User\UserBaseController;
use App\Models\Players;
use App\Models\User;
use Illuminate\Http\Request;

class IndexController extends UserBaseController
{
    public function __constructor()
    {
        parent::__constructor(); // TODO: Change the autogenerated stub
    }

    /**
     * @return \Illuminate\Contracts\Foundation\Application|\Illuminate\Contracts\View\Factory|\Illuminate\Contracts\View\View
     */
    public function index()
    {
        $test=    \DB::table('user_players')
                ->where('user_id', '=', \Auth::id())
                ->get()->pluck('player_id');

       return view('groups.user.pages.myTeam.index', [
           'user' => User::with('players.team')->find( \Auth::id() ),
           'players' => Players::with('team')
               ->whereNotIn('id', $test)
               ->get()
       ]);
    }

    public function addPlayer(Request $request)
    {
        $user = User::with('players')->find(\Auth::id());
        if ($user->players()->attach($request->player_id) === null)
        {
            return redirect()->back();
        } else{
            abort(500);
        }

    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}
